// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "RSH.h"

namespace plugin {
namespace Bro_RSH {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("RSH",
		             ::analyzer::rsh::RSH_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::RSH";
		config.description = "RSH Protocol analyzer";
		return config;
		}
} plugin;

}
}