# Generated by binpac_quickstart

refine flow NNTP_Flow += {
	function proc_nntp_message(msg: NNTP_PDU): bool
		%{
		BifEvent::generate_nntp_event(connection()->bro_analyzer(), connection()->bro_analyzer()->Conn(),
new StringVal(${msg.command}.length(), (const char*) ${msg.command}.begin()),
new StringVal(${msg.arg}.length(), (const char*) ${msg.arg}.begin()));
		return true;
		%}
};

refine typeattr NNTP_PDU += &let {
	proc: bool = $context.flow.proc_nntp_message(this);
};
