// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "NNTP.h"

namespace plugin {
namespace Bro_NNTP {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("NNTP",
		             ::analyzer::nntp::NNTP_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::NNTP";
		config.description = "NNTP analyzer";
		return config;
		}
} plugin;

}
}