// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_POPPASSD_POPPASSD_H
#define ANALYZER_PROTOCOL_POPPASSD_POPPASSD_H

#include "events.bif.h"


#include "analyzer/protocol/tcp/TCP.h"

#include "poppassd_pac.h"

namespace analyzer { namespace poppassd {

class POPPASSD_Analyzer

: public tcp::TCP_ApplicationAnalyzer {

public:
	POPPASSD_Analyzer(Connection* conn);
	virtual ~POPPASSD_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();
	
	virtual void DeliverStream(int len, const u_char* data, bool orig);
	virtual void Undelivered(uint64 seq, int len, bool orig);

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	virtual void EndpointEOF(bool is_orig);
	

	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new POPPASSD_Analyzer(conn); }

protected:
	binpac::POPPASSD::POPPASSD_Conn* interp;
	
	bool had_gap;
	
};

} } // namespace analyzer::* 

#endif