// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "RLOGIN_.h"

namespace plugin {
namespace Bro_RLOGIN_ {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("RLOGIN_",
		             ::analyzer::rlogin_::RLOGIN__Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::RLOGIN_";
		config.description = "RLOGIN Protocol 2 analyzer";
		return config;
		}
} plugin;

}
}