// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "TACACS.h"

namespace plugin {
namespace Bro_TACACS {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("TACACS",
		             ::analyzer::tacacs::TACACS_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::TACACS";
		config.description = "tacacs analyzer";
		return config;
		}
} plugin;

}
}