// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_TACACS_TACACS_H
#define ANALYZER_PROTOCOL_TACACS_TACACS_H

#include "events.bif.h"


#include "analyzer/protocol/tcp/TCP.h"

#include "tacacs_pac.h"

namespace analyzer { namespace tacacs {

class TACACS_Analyzer

: public tcp::TCP_ApplicationAnalyzer {

public:
	TACACS_Analyzer(Connection* conn);
	virtual ~TACACS_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();
	
	virtual void DeliverStream(int len, const u_char* data, bool orig);
	virtual void Undelivered(uint64 seq, int len, bool orig);

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	virtual void EndpointEOF(bool is_orig);
	

	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new TACACS_Analyzer(conn); }

protected:
	binpac::TACACS::TACACS_Conn* interp;
	
	bool had_gap;
	
};

} } // namespace analyzer::* 

#endif