// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_POSTGRESQL_POSTGRESQL_H
#define ANALYZER_PROTOCOL_POSTGRESQL_POSTGRESQL_H

#include "events.bif.h"


#include "analyzer/protocol/tcp/TCP.h"

#include "postgresql_pac.h"

namespace analyzer { namespace postgresql {

class POSTGRESQL_Analyzer

: public tcp::TCP_ApplicationAnalyzer {

public:
	POSTGRESQL_Analyzer(Connection* conn);
	virtual ~POSTGRESQL_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();
	
	virtual void DeliverStream(int len, const u_char* data, bool orig);
	virtual void Undelivered(uint64 seq, int len, bool orig);

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	virtual void EndpointEOF(bool is_orig);
	

	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new POSTGRESQL_Analyzer(conn); }

protected:
	binpac::POSTGRESQL::POSTGRESQL_Conn* interp;
	
	bool had_gap;
	
};

} } // namespace analyzer::* 

#endif