// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "TELNET_.h"

namespace plugin {
namespace Bro_TELNET_ {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("TELNET_",
		             ::analyzer::telnet_::TELNET__Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::TELNET_";
		config.description = "Telnet_ analyzer";
		return config;
		}
} plugin;

}
}