// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "RLOGIN.h"

namespace plugin {
namespace Bro_RLOGIN {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("RLOGIN",
		             ::analyzer::rlogin::RLOGIN_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::RLOGIN";
		config.description = "RLOGIN Protocol analyzer";
		return config;
		}
} plugin;

}
}