// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_LDAP_LDAP_H
#define ANALYZER_PROTOCOL_LDAP_LDAP_H

#include "events.bif.h"


#include "analyzer/protocol/tcp/TCP.h"

#include "ldap_pac.h"

namespace analyzer { namespace ldap {

class LDAP_Analyzer

: public tcp::TCP_ApplicationAnalyzer {

public:
	LDAP_Analyzer(Connection* conn);
	virtual ~LDAP_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();
	
	virtual void DeliverStream(int len, const u_char* data, bool orig);
	virtual void Undelivered(uint64 seq, int len, bool orig);

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	virtual void EndpointEOF(bool is_orig);
	

	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new LDAP_Analyzer(conn); }

protected:
	binpac::LDAP::LDAP_Conn* interp;
	
	bool had_gap;
	
};

} } // namespace analyzer::* 

#endif