// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_RLOGIN_RLOGIN_H
#define ANALYZER_PROTOCOL_RLOGIN_RLOGIN_H

#include "events.bif.h"


#include "analyzer/protocol/tcp/TCP.h"

#include "rlogin_pac.h"

namespace analyzer { namespace rlogin {

class RLOGIN_Analyzer

: public tcp::TCP_ApplicationAnalyzer {

public:
	RLOGIN_Analyzer(Connection* conn);
	virtual ~RLOGIN_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();
	
	virtual void DeliverStream(int len, const u_char* data, bool orig);
	virtual void Undelivered(uint64 seq, int len, bool orig);

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	virtual void EndpointEOF(bool is_orig);
	

	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new RLOGIN_Analyzer(conn); }

protected:
	binpac::RLOGIN::RLOGIN_Conn* interp;
	
	bool had_gap;
	
};

} } // namespace analyzer::* 

#endif