// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_RSH_RSH_H
#define ANALYZER_PROTOCOL_RSH_RSH_H

#include "events.bif.h"


#include "analyzer/protocol/tcp/TCP.h"

#include "rsh_pac.h"

namespace analyzer { namespace rsh {

class RSH_Analyzer

: public tcp::TCP_ApplicationAnalyzer {

public:
	RSH_Analyzer(Connection* conn);
	virtual ~RSH_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();
	
	virtual void DeliverStream(int len, const u_char* data, bool orig);
	virtual void Undelivered(uint64 seq, int len, bool orig);

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	virtual void EndpointEOF(bool is_orig);
	

	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new RSH_Analyzer(conn); }

protected:
	binpac::RSH::RSH_Conn* interp;
	
	bool had_gap;
	
};

} } // namespace analyzer::* 

#endif