# Generated by binpac_quickstart

refine flow POPPASSD_Flow += {

	function proc_poppassd_message(msg: POPPASSD_PDU): bool
		%{
	
	   	BifEvent::generate_poppassd_event_debug(connection()->bro_analyzer(), connection()->bro_analyzer()->Conn(),
			new StringVal(${msg.data}.length(), (const char*)${msg.data}.begin())
			);

		return true;
		%}
};

refine typeattr POPPASSD_PDU += &let {
	proc: bool = $context.flow.proc_poppassd_message(this);
};