// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "CVS.h"

namespace plugin {
namespace Bro_CVS {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("CVS",
		             ::analyzer::cvs::CVS_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::CVS";
		config.description = "CVS analyzer";
		return config;
		}
} plugin;

}
}