// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "IMAP.h"

namespace plugin {
namespace Bro_IMAP {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("IMAP",
		             ::analyzer::IMAP::IMAP_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::IMAP";
		config.description = "IMAP Protocol analyzer";
		return config;
		}
} plugin;

}
}