# Generated by binpac_quickstart

refine flow LOL_Flow += {
	function proc_lol_message(msg: LOL_PDU): bool
		%{
		BifEvent::generate_lol_event(connection()->bro_analyzer(), connection()->bro_analyzer()->Conn());
		return true;
		%}
};

refine typeattr LOL_PDU += &let {
	proc: bool = $context.flow.proc_lol_message(this);
};