// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_LOL_LOL_H
#define ANALYZER_PROTOCOL_LOL_LOL_H

#include "events.bif.h"


#include "analyzer/protocol/tcp/TCP.h"

#include "lol_pac.h"

namespace analyzer { namespace lol {

class LOL_Analyzer

: public tcp::TCP_ApplicationAnalyzer {

public:
	LOL_Analyzer(Connection* conn);
	virtual ~LOL_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();
	
	virtual void DeliverStream(int len, const u_char* data, bool orig);
	virtual void Undelivered(uint64 seq, int len, bool orig);

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	virtual void EndpointEOF(bool is_orig);
	

	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new LOL_Analyzer(conn); }

protected:
	binpac::LOL::LOL_Conn* interp;
	
	bool had_gap;
	
};

} } // namespace analyzer::* 

#endif