// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "LOL.h"

namespace plugin {
namespace Bro_LOL {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("LOL",
		             ::analyzer::lol::LOL_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::LOL";
		config.description = "The LoL Protocol analyzer";
		return config;
		}
} plugin;

}
}