// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "POPPASSD.h"

namespace plugin {
namespace Bro_POPPASSD {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("POPPASSD",
		             ::analyzer::poppassd::POPPASSD_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::POPPASSD";
		config.description = "Poppassd Protocol analyzer";
		return config;
		}
} plugin;

}
}